obj-m += xeth.o

xeth-y := xeth_mod.o
xeth-y += xeth_mux.o
xeth-y += xeth_proxy.o
xeth-y += xeth_bridge.o
xeth-y += xeth_lb.o
xeth-y += xeth_lag.o
xeth-y += xeth_vlan.o
xeth-y += xeth_port.o
xeth-y += xeth_nb.o
xeth-y += xeth_sbrx.o
xeth-y += xeth_sbtx.o
xeth-$(CONFIG_I2C) += xeth_qsfp.o
xeth-y += xeth_version.o

-include $(src)/xeth_version.mk
ifneq ($(XETH_VERSION),)
ccflags-y += -DXETH_VERSION=\"$(XETH_VERSION)\"
endif

xeth-srctree-uapi := $(srctree)/include/uapi/linux/xeth.h
xeth-uapi := $(or $(wildcard $(src)/xeth_uapi.h),$(xeth-srctree-uapi))
ccflags-y += --include=$(xeth-uapi)
ccflags-y += --include=$(src)/xeth.h
